server:
  port: 9100 # server port

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:todolist # h2 database address
    driver-class-name: org.h2.Driver # set up driver
    username: boris # database user name
    password:  # database password

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  thymeleaf:
    cache: false
    prefix: classpath:/templates/    # find html file in templates folder
    suffix: .html
    encoding: UTF-8
    mode: HTML5